# Generated by Django 3.1.1 on 2020-09-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author',
            new_name='name',
        ),
    ]
